[project]
name = "initial-charms-implement"
version = "0.0.1"
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "ruff",
    "ty",
]

[tool.ruff]
format.quote-style = "single"
line-length = 99
