name: Charm checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  charm-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Check kubernetes
        run: |
          cd kubernetes
          tox -e lint,unit
      - name: Check kubernetes-extra
        run: |
          cd kubernetes-extra
          tox -e lint,unit
      - name: Check machine
        run: |
          cd machine
          tox -e lint,unit
