name: Charm integration tests

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  charm-integration-tests-machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Install Concierge
        run: sudo snap install --classic concierge
      - name: Prepare for deploying machine charms
        run: sudo concierge prepare -p machine
      - name: Pack charm
        run: |
          cd machine
          charmcraft pack
      - name: Run integration tests
        run: |
          cd machine
          tox -e integration
