name: Current with Charmcraft

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  current:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5
        with:
          path: initial-charms
      - name: Checkout this repo
        uses: actions/checkout@v5
        with:
          repository: canonical/charmcraft
          path: charmcraft
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Charmcraft
        run: |
          cd charmcraft
          make setup
      # - name: Implement kubernetes-extra
      #   run: uvx --from rust-just just kubernetes-extra
      # - name: Make sure nothing changed
      #   run: git diff --exit-code
